CONFIG_STDOUT_CONSOLE=y
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_LSM6DSO_TRIGGER_GLOBAL_THREAD=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_SHELL=y
CONFIG_I2C_SHELL=y
CONFIG_LSM6DSO=y
CONFIG_LOG=y

CONFIG_THREAD_NAME=y
CONFIG_MULTITHREADING=y
# CONFIG_THREAD_MONITOR=y
# CONFIG_THREAD_ANALYZER=y
# CONFIG_THREAD_ANALYZER_USE_LOG=y
CONFIG_LOG_THREAD_ID_PREFIX=y